/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_winplus_serial_utils_SerialPort */

#ifndef _Included_org_winplus_serial_utils_SerialPort
#define _Included_org_winplus_serial_utils_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT  jint JNICALL Java_com_yfcomm_pos_SerialPort_open
  (JNIEnv *, jclass, jstring ,jint);

JNIEXPORT jint JNICALL Java_com_yfcomm_pos_SerialPort_sel
(JNIEnv *env, jclass thiz,jint fd);


JNIEXPORT jint JNICALL Java_com_yfcomm_pos_SerialPort_send
(JNIEnv *env, jclass thiz,jint fd, jbyteArray sendbuf, jint data_len);

JNIEXPORT jint JNICALL Java_com_yfcomm_pos_SerialPort_rcv
(JNIEnv *env, jclass thiz,jint fd, jbyteArray rcvbuf,jint data_len,jint speed);

JNIEXPORT jint JNICALL Java_com_yfcomm_pos_SerialPort_set
  (JNIEnv *env, jclass thiz,jint fd, jint speed,jint flow_ctrl,jint databits,jint stopbits,jint parity);


/*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yfcomm_pos_SerialPort_close
  (JNIEnv *env, jobject thiz,jint  fd);

#ifdef __cplusplus
}
#endif
#endif
